Add everyone's subteam and project descriptions
HIRO-group/HIRO-group.github.io pull request #127
Opened 2021-03-16 22:08 UTC by joewie

Barebones update, I assume @alecive will eventually want to restructure stuff properly!

2021-03-16 22:39 UTC, joewie commented
Links are broken in deploy preview (but should work when live). Please preview the subteam pages at:

- https://deploy-preview-127--cranky-jackson-a3e285.netlify.app/subteam/algorithmic-social-hri
- https://deploy-preview-127--cranky-jackson-a3e285.netlify.app/subteam/control-artificial-skin
- https://deploy-preview-127--cranky-jackson-a3e285.netlify.app/subteam/learning-modeling-robotics

2021-03-17 14:16 UTC, alecive approved these changes

2021-03-17 14:23 UTC, alecive requested changes
I'm fixing it

2021-03-17 15:41 UTC, alecive approved these changes

2021-03-17 15:42 UTC, merged