Add Noah to people page
HIRO-group/HIRO-group.github.io pull request #190
Opened 2023-06-14 00:16 UTC by noli3118

2023-06-14 00:59 UTC, joewie requested changes
Image file seems to be empty.

2023-06-14 21:58 UTC, alecive commented
@noli3118 as per instructions: the picture should be square! 

Also, please remove the black borders from it.

2023-06-14 21:59 UTC, alecive requested changes

2023-06-14 21:59 UTC, alecive commented on img/people/noah.jpg
this file should be removed if you won't use it.

2023-06-14 21:59 UTC, alecive commented on img/people/noah.png
this file should be square , and you should remove the border.

2023-06-14 21:59 UTC, alecive commented on _data/people.yml
> +   pic: noah.jpg
if you are using the png, this should point to the png picture.

2023-06-26 22:06 UTC, alecive commented
Nice! Good job.

2023-06-26 22:07 UTC, alecive commented
@noli3118 unfortunately, because this PR too too long, there are now conflicts in the `people.yml` file. Please synchronize with @calebescobedo and have him resolve them as these thigns are tricky.

2023-07-03 12:38 UTC, alecive requested changes

2023-07-03 12:38 UTC, alecive commented on _data/people.yml
> +>>>>>>> 2e45997d69a8389896705e633dc7f498d439376c
I see there are still conflicts. I recommend you close this PR, you `pull --rebase` the repo and open a new one. @calebescobedo

2023-07-03 12:38 UTC, closed without merging