Add Caleb Kumar Picture to website
HIRO-group/HIRO-group.github.io pull request #192
Opened 2023-06-14 20:52 UTC by cekcreator

Add my picture to lab website

2023-06-14 22:01 UTC, alecive requested changes

2023-06-14 22:01 UTC, alecive commented on _data/people.yml
> +   role: Undergrad
This should be lowercase

2023-06-14 22:01 UTC, alecive commented on img/people/caleb_kumar.jpg
While this is a great picture, it should be square!

2023-06-15 16:01 UTC, cekcreator commented on img/people/caleb_kumar.jpg
I edited the picture to be as square as possible, let me know if it still does not work. If it does not ill find another one to use!

2023-06-15 18:02 UTC, alecive requested changes

2023-06-15 18:02 UTC, alecive commented on img/people/caleb_kumar.jpg
Unfortunately, it needs to be exactly square. Also, it's too big and it needs to be 400x400 pixels at most. Please coordinate with your supervisor (@calebescobedo ?) , he'll show you how to do it!

2023-06-15 18:02 UTC, alecive commented on _data/people.yml
> +   role: Undergrad
We still have problems for some reason:

![image](https://github.com/HIRO-group/HIRO-group.github.io/assets/4378663/b6b7ca31-b264-43b7-97de-29d870e2d939)

2023-06-16 15:13 UTC, alecive requested changes

2023-06-16 15:13 UTC, alecive commented on _data/people.yml
> +   pic: caleb_kumar.jpg
ok last thing: this should be the name of your image file! Eitehr change this or the image filename.

2023-06-19 17:55 UTC, alecive commented
I think we are now done! Good job @cekcreator

2023-06-19 17:55 UTC, alecive approved these changes

2023-06-19 17:55 UTC, merged