[jake] Updated task assignment research blurb.
HIRO-group/HIRO-group.github.io pull request #211
Opened 2023-12-21 19:37 UTC by JakeBrawer

2023-12-21 20:20 UTC, alecive requested changes

2023-12-21 20:20 UTC, alecive commented on _posts/research/subteams/2021-03-16-algorithmic-social-hri.md
> +**Postdoc:** [Jake Brawer](https://jakebrawer.com/)
Add newline

2023-12-21 20:20 UTC, alecive commented on _posts/research/subteams/2021-03-16-algorithmic-social-hri.md
> +## 1.4 Interactive Task and Role Assignment for Human Robot Collaboration
move it up -- maybe 1.2? Right below stephane's

2023-12-21 20:20 UTC, alecive commented on _posts/research/subteams/2021-03-16-algorithmic-social-hri.md
> +Our ongoing work seeks to narrow the gap between human ingenuity and algorithmic efficiency by enabling users to shape, update, and modify TAS systems entirely via LLm-mediated, interactive dialogue.
typo: LLm -> LLM

2023-12-21 20:20 UTC, alecive commented on _posts/research/subteams/2021-03-16-algorithmic-social-hri.md
> +We hope this work  This approach not only enhances the efficiency and flexibility of task management, but also democratizes the use of advanced TAS algorithms.
You don't "hope" --> be more assertive.

2023-12-21 20:20 UTC, alecive commented on _posts/research/subteams/2021-03-16-algorithmic-social-hri.md
> +**Students:** [Kaleb Bishop](https://kalebishop.github.io/)
Add publications here

2023-12-23 00:34 UTC, alecive commented
I don't think you did all I asked above right?

2023-12-23 14:59 UTC, JakeBrawer commented
> I don't think you did all I asked above right?
Sorry I think it should be good now.

2024-01-12 20:32 UTC, JakeBrawer commented
I think I've made all these changes have I not?

2024-01-12 20:45 UTC, alecive approved these changes

2024-01-12 20:45 UTC, merged